name: CI

permissions:
  statuses: write
  pages: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/jod"
          registry-url: 'https://registry.npmjs.org'

      - name: npm install
        run: npm ci

      - name: lint
        run: npm run lint

      - name: jest
        run: npm run test
      
      - name: build
        run: npm run build

      - name: Setup Pages
        if: github.ref_name == github.event.repository.default_branch
        uses: actions/configure-pages@v5
  
      - name: Upload artifact
        if: github.ref_name == github.event.repository.default_branch
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/
  
      - name: Deploy to GitHub Pages
        if: github.ref_name == github.event.repository.default_branch
        uses: actions/deploy-pages@v4


  
