name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  pages: write
  id-token: write
  contents: read
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/jod"
          registry-url: 'https://registry.npmjs.org'

      - name: npm install
        run: npm ci

      - name: lint
        run: npm run lint

      - name: jest
        run: npm run test
      
      - name: build
        run: npm run build

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Setup Pages
        if: github.ref_name == github.event.repository.default_branch
        uses: actions/configure-pages@v5
        with:
          token: ${{ steps.app-token.outputs.token }}
  
      - name: Upload artifact
        if: github.ref_name == github.event.repository.default_branch
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/
  
      - name: Deploy to GitHub Pages
        if: github.ref_name == github.event.repository.default_branch
        uses: actions/deploy-pages@v4
        with:
          token: ${{ steps.app-token.outputs.token }}


  
